config:
  mdIt:
    - "@mdit/plugin-attrs"
    - "@mdit/plugin-mark"

locales:
  /:
    lang: en-US
    langName: EN
    title: Cheng Shang | Homepage
    description: I conduct research in Quantum Theory.
    ui:
      themeToggle: Toggle Theme
      contact: Contact

    hero:
      name: Cheng Shang
      welcome: 👋 Hi there, I am
      titles:
        - ℏ Theoretical Physics Researcher
        - ♜ INTJ (MBTI) ➶ Sagittarius
        - (๑˃ᴗ˂)ﻭ What matters most to me is not success, but whether I have found my own path in life.
        - (￣ー￣)💭 Understanding the fundamental principles governing nature and building world.
      avatar: /avatar.avif
      bgImage: /bg.avif
      medias:
        - icon: fa6-brands:orcid
          name: ORCID
          link: https://orcid.org/0000-0001-8393-2329

        - icon: fa6-brands:google-scholar
          name: Google Scholar
          link: https://scholar.google.com/citations?user=-k8PWr8AAAAJ

        - icon: fa6-brands:linkedin-in
          name: iNSPIRE
          link: https://inspirehep.net/authors/2662928

        - icon: fa6-solid:fire
          name: "Make time for civilization. Live proud. Never give up!"
          link: https://cheng-shang.me/

    navbar:
      links:
        - label: Profile
          anchor: "#profile"
        - label: Experience
          anchor: "#experience"
        - label: Achievements
          anchor: "#achievements"
        - label: Interests
          anchor: "#interests"

    sections:
      - type: profile
        id: profile
        title: Profile
        icon: user-tie
        data:
          fields:
            - title: Affiliation
              icon: building-columns
              value: Analytical Quantum Complexity RIKEN Hakubi Research Team |RIKEN Center for Quantum Computing
            - title: Position
              icon: user-graduate
              value: Postdoctoral Researcher (๑˃ᴗ˂)ﻭ☕📄🎉

          contacts:
            - label: RIKEN Email
              value: cheng.shang@riken.jp
              icon: fa6-solid:envelope

            - label: Gmail
              value: shangc1204@gmail.com
              icon: fa6-brands:google

            - label: Gmail
              value: shangcheng.phys@gmail.com

            - label: X |Social Media
              value: "@Shangc1204"
              link: https://x.com/Shangc1204
              icon: fa6-brands:x-twitter

      - type: experience
        id: experience
        title: Experience
        icon: briefcase
        data:
          - type: work
            place: Wako, Saitama, Japan
            time: Oct. 2024 - Present
            title: Postdoctoral Researcher
            content: with Dr. [Tomotaka Kuwahara](https://kuwahara-quantum.com/en/)
            description: Analytical Quantum Complexity RIKEN Hakubi Research Team, RIKEN Center for Quantum Computing

          - type: work
            place: Wako, Saitama, Japan
            time: Apr. 2023 - Sep. 2024
            title: Part-time Positions at RIKEN
            content: Junior Research Associate Program with Dr. [Tomotaka Kuwahara](https://kuwahara-quantum.com/en/)
            description: Analytical Quantum Complexity RIKEN Hakubi Research Team, RIKEN Center for Quantum Computing

          - type: study
            place: Kashiwa, Chiba, Japan
            time: Oct. 2021 - Sep. 2024
            title: Ph.D. |The University of Tokyo, Department of Physics
            content: Japanese Government (MEXT) Doctoral Scholarship with Prof. [Naomichi Hatano](http://hatano-lab.iis.u-tokyo.ac.jp/index-e.html)

          - type: study
            place: Changchun, Jilin, China
            time: Oct. 2020 - Aug. 2021
            title: MEXT Doctoral Scholarship Candidate
            content: Preparatory School for Chinese Students to Japan

          - type: study
            place: Changchun, Jilin, China
            time: Sep. 2017 - June 2020
            title: Master of Science |Northeast Normal University, Center for Quantum Sciences
            content: Chinese National Scholarship for Postgraduates with Prof. [XueXi Yi](https://cqs.nenu.edu.cn/)

      - type: banner
        id: cfp
        title: Call for Papers
        icon: bullhorn
        data:
          tags: Call for Papers
          header: |-
            Special Collection: Exception Points in non-Hermitian Systems
          content: |-
            **Journal**: Discover Physics (Springer Nature)
            For inquiries, please contact: cheng.shang@riken.jp or shenhz458@nenu.edu.cn
          footer: |-
            Submission Deadline: 21 April, 2026
          actions:
            - label: Submit & Learn More
              link: https://link.springer.com/collections/djheehghia
              primary: true

      - type: list
        id: achievements
        title: Selected Publications
        icon: scroll
        data:
          - |-
            [Zhi-Guang Lu, Guo-Qing Tian, Xin-You Lü, and ==Cheng Shang==, _Topological Quantum Batteries_, **Phys. Rev. Lett.** **134**, 180401 (2025).](https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.134.180401)

            This work was featured in [PRL Trending](https://x.com/PhysRevLett/status/1924474721149542443), highlighted in a Press Release by [RIKEN](https://www.riken.jp/en/news_pubs/research_news/pr/2025/20250513_2/index.html), and presented as an Invited Talk at the [21st International Workshop on Pseudo-Hermitian Hamiltonians in Quantum Physics (PHHQP-XXI)](https://events.physics.uoc.gr/event/1/page/5-speakers), Chania, Greece. As of February 2026, this study has 82 citations on Google Scholar. {.desc}

          - |-
            [==Cheng Shang== and Hong-Chao Li, _Resonance-dominant optomechanical entanglement in open quantum systems_, **Physical Review Applied** **21**(4), 044048 (2024).](https://journals.aps.org/prapplied/abstract/10.1103/PhysRevApplied.21.044048)

            This work was an Independent Research project conducted by only two graduate students. As of February 2026, this study has 22 citations on Google Scholar. {.desc}

          - |-
            [==Cheng Shang==, Hong-Zhi Shen, and Xue-Xi Yi, _Nonreciprocity in a strongly coupled three-mode optomechanical circulatory system_, **Optics Express** **27**(18), 25882–25901 (2019).](https://opg.optica.org/oe/fulltext.cfm?uri=oe-27-18-25882&id=417227)

            As of February 2026, this work has received 35 citations on Google Scholar. {.desc}

          - |-
            [Hong-Zhi Shen, ==Cheng Shang==, Y. H. Zhou, and Xue-Xi Yi, _Unconventional single-photon blockade in non-Markovian systems_, **Phys. Rev. A** **98**(2), 023856 (2018).](https://journals.aps.org/pra/abstract/10.1103/PhysRevA.98.023856)

            As of February 2026, this work has received 97 citations on Google Scholar. {.desc}

          - |-
            [Zhi-Guang Lu, ==Cheng Shang==, Ying Wu, and Xin-You Lü, _Analytical approach to higher-order correlation functions in U(1) symmetric systems_, **Phys. Rev. A** **108**, 053703 (2023).](https://journals.aps.org/pra/abstract/10.1103/PhysRevA.108.053703)

            This work developed a user-friendly open-source library in Python known as the [Quantum Correlation Solver](https://github.com/ZhiGuangLu/qcs). {.desc}

          - |-
            [==Cheng Shang== and H. Z. Shen, _Coupling Enhancement and Symmetrization in Dissipative Optomechanical Systems_, **Annalen der Physik** **538**, e00606 (2026).](https://onlinelibrary.wiley.com/doi/10.1002/andp.202500606)

            An invited contribution to _Annalen der Physik_. {.desc}

      - type: list
        id: preprints
        title: Selected Preprints
        icon: clock-rotate-left
        data:
          - |-
            [==Cheng Shang==, Zhi-Guang Lu, Hayato Kinkawa, and Tomotaka Kuwahara, _Operator Spreading and Information Propagation: Equivalence and Beyond_, **arXiv**:2505.07955.](https://arxiv.org/abs/2505.07955)

            This work received the <a href="http://en.baqis.ac.cn/news/detail/?cid=1764" target="_blank" rel="noopener noreferrer">Best Poster Award</a> at the 5th International Symposium on Quantum Physics and Quantum Information Sciences (QPQIS-2023), Beijing, China. This work is currently under review at _PRA Letter_. {.desc}

          - |-
            [Donghoon Kim, Yusuke Kimura, Hugo Mackay, Yosuke Mitsuhashi, Hideaki Nishikawa, Carla Rubiliani, ==Cheng Shang== _(Authors are listed in alphabetical order)_, Ayumi Ukai, and Tomotaka Kuwahara, _Spectral Small-Incremental-Entangling: Breaking Quasi-Polynomial Complexity Barriers in Long-Range Interacting Systems_, **arXiv**:2509.12014.](https://arxiv.org/abs/2509.12014)

            This work, an International Collaboration across Asia, Europe, and the U. S., introduces the concept of spectral entangling strength (SIE), which captures the structural entangling power of an operator, and establishes a spectral SIE theorem. This manuscript is currently under review at _Physical Review X_. {.desc}

          - |-
            [Hongchao Li, ==Cheng Shang==, Tomotaka Kuwahara, and Tan Van Vu, _Macroscopic Particle Transport in Dissipative Long-Range Bosonic Systems_, **arXiv**:2503.13731.](https://arxiv.org/abs/2503.13731)

            This work has been accepted for publication in _Nature Communications_. {.desc}

          - |-
            [Rohit Kumar Shukla and ==Cheng Shang==, _Many-Body Structural Effects in Periodically Driven Quantum Batteries_, **arXiv**:2603.03883.](https://arxiv.org/abs/2603.03883)

            This work study how many-body structure affects charging optimization under a periodic driving protocol, showing that integrability breaking and long-range interactions serve as key points for improving the QBs charging performance_. {.desc}

          - |-
            [H. Z. Shen, X. C. Zhang, L. Y. Ning, Zhi-Guang Lu, Yan-Hui Zhou, and ==Cheng Shang==, _Higher-order Exceptional Points Induced by Non-Markovian Environments_, **arXiv**:2504.00617.](https://arxiv.org/abs/2504.00617)

            This work is currently under review at _Laser & Photonics Reviews_. {.desc}

      - type: list
        id: interests
        title: Research Interests
        icon: flask
        dot: check
        data:
          - "**▼ Lieb-Robinson Bound and Its Application**: one may include Particle Transport, Information Propagation, Operator Spreading, and Correlation Generation."
          - "**▣ Open Quantum Systems**: with particular focus on Dissipative and non-Markovian Dynamics in Quantum Optics and Quantum Information."
          - "**◎ Quantum Batteries**: focuses on improving the performance of Quantum Batteries by addressing theoretical barriers in practical applications, including those in Topological few-body and Many-Body Quantum Systems."
          - "**|◻︎| Hybrid Cavity Optomechanics**: theoretical exploration of nonlinear radiation-pressure-induced phenomena and their integration with Superconducting Circuit platforms."

      - type: list
        id: future
        title: What I Want to Learn
        icon: fa6-solid:book
        dot: check
        data:
          - text: "**Many-body localization and thermalization** (from an information-theoretic perspective) _Currently studying_"
          - text: "**Floquet theory** (Periodic driving and Floquet heating) _Currently studying_"
          - text: "**Hamiltonian complexity and Krylov complexity**"
          - text: "**Advanced mathematics** (e.g., von Neumann algebras and Graph theory)"
          - text: "**Cosmology** (e.g., Inflation theory and dS/CFT)"

      - type: markdown
        id: hobbies
        title: Hobbies
        icon: fa6-solid:heart
        data:
          content: ✎ Sketching; Writing fiction; ♪ Music; Comics; Hip-hop dance......

      - type: markdown
        id: closing
        title: Welcome
        icon: fa6-solid:star
        data:
          content: |-
            If you are interested in my research, feel free to contact me.

            Academic discussions and potential collaborations are always welcome!

    footer:
      copyright: |-
        © 2026 Cheng Shang. All rights reserved.

        ⟳ Update: February, 2026
