virtualStoreType: global

minimumReleaseAgeExclude:
  - "@mdit/*"
  - "@mr-hope/*"
  - "@oxfmt/*"
  - "@oxlint/*"
  - "@vitest/*"
  - "@vue/*"
  - "oxc-config-hope"
  - "oxfmt"
  - "oxlint"

trustPolicy: no-downgrade

minimumReleaseAgeExcludePrune: true
trustPolicyExcludePrune: true
trustPolicyIgnoreAfter: 720
